blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://zouyaoji.top/vue-cesium/#/en/issues
    about: The issue which is not created via https://zouyaoji.top/vue-cesium/#/en/issues will be closed immediately.
